chore: add a vagrant config for testing
quipucords/quipucords-installer pull request #15
Opened 2024-07-16 21:48 UTC by bruno-fs

I used these images to play around with the installer. Might be useful for more people.

2024-07-16 22:59 UTC, abellotti commented
I think that's fine 👍  do you need installed with the RPM (mentioned in the spec file) or just running from source/git ?

2024-07-16 23:16 UTC, bruno-fs commented
only needed when running from source. I think adding it to the RPM would be too much

2024-07-16 23:18 UTC, abellotti approved these changes

2024-07-17 13:52 UTC, infinitewarp requested changes
I'd like to see a README or DEVELOPMENT doc or at least some inline comments somewhere to explain to future readers why this Vagrantfile exists. Otherwise, it seems really strange and unexpected to be here.

2025-08-20 10:53 UTC, closed without merging